import type { TrendTopic } from "./trend-scouting.types";

export const TREND_TOPICS: TrendTopic[] = [
  {
    id: "funny-pets-chaos",
    title: "Top mascotas causando caos",
    category: "Animales",
    angle: "clips de mascotas con remate visual inmediato",
    baseScore: 86,
    safetyScore: 92,
    retentionScore: 88,
    clipAvailabilityScore: 94,
    keywords: ["funny pets", "pet fails", "animals being chaotic", "mascotas graciosas"],
    avoid: ["clips con animales lastimados", "maltrato", "situaciones peligrosas"],
  },
  {
    id: "unexpected-fails",
    title: "Top fails inesperados",
    category: "Fails",
    angle: "momentos donde todo parece normal y sale mal en 1 segundo",
    baseScore: 89,
    safetyScore: 78,
    retentionScore: 93,
    clipAvailabilityScore: 90,
    keywords: ["unexpected fails", "funny fails", "instant regret", "fails graciosos"],
    avoid: ["accidentes graves", "lesiones", "humillacion cruel"],
  },
  {
    id: "caught-on-camera",
    title: "Top cosas captadas en camara",
    category: "Curiosidades",
    angle: "situaciones raras o sorprendentes que parecen irrepetibles",
    baseScore: 84,
    safetyScore: 84,
    retentionScore: 89,
    clipAvailabilityScore: 83,
    keywords: ["caught on camera", "rare moments", "unbelievable moments", "captado en camara"],
    avoid: ["crimen real grafico", "emergencias", "desinformacion"],
  },
  {
    id: "viral-gadgets",
    title: "Top gadgets virales",
    category: "Gadgets",
    angle: "productos que hacen algo visualmente raro, util o satisfactorio",
    baseScore: 80,
    safetyScore: 90,
    retentionScore: 82,
    clipAvailabilityScore: 80,
    keywords: ["viral gadgets", "amazon finds", "cool gadgets", "gadgets virales"],
    avoid: ["claims medicos", "productos peligrosos", "marcas falsas"],
  },
  {
    id: "weird-food",
    title: "Top comidas raras virales",
    category: "Comida",
    angle: "preparaciones extranas, gigantes o visualmente satisfactorias",
    baseScore: 79,
    safetyScore: 87,
    retentionScore: 84,
    clipAvailabilityScore: 82,
    keywords: ["weird food", "viral food", "street food", "comida rara"],
    avoid: ["contenido asqueroso extremo", "riesgos sanitarios", "desperdicio exagerado"],
  },
  {
    id: "people-are-amazing",
    title: "Top personas haciendo cosas increibles",
    category: "Habilidades",
    angle: "habilidades visuales que se entienden sin contexto",
    baseScore: 82,
    safetyScore: 86,
    retentionScore: 88,
    clipAvailabilityScore: 78,
    keywords: ["people are amazing", "insane skills", "talent clips", "habilidades increibles"],
    avoid: ["retos peligrosos", "acrobacias de alto riesgo", "menores en peligro"],
  },
  {
    id: "sports-weird-moments",
    title: "Top momentos raros del deporte",
    category: "Deportes",
    angle: "jugadas, celebraciones o errores que tienen remate claro",
    baseScore: 78,
    safetyScore: 80,
    retentionScore: 86,
    clipAvailabilityScore: 72,
    keywords: ["weird sports moments", "sports funny moments", "sports fails", "momentos raros deporte"],
    avoid: ["lesiones", "peleas", "clips de transmisiones con mucho copyright"],
  },
  {
    id: "gaming-clips",
    title: "Top clips de gaming del momento",
    category: "Gaming",
    angle: "jugadas absurdas, bugs o fails que se entienden rapido",
    baseScore: 77,
    safetyScore: 85,
    retentionScore: 81,
    clipAvailabilityScore: 86,
    keywords: ["gaming clips", "funny gaming moments", "game fails", "clips gaming"],
    avoid: ["lenguaje ofensivo", "slurs", "clips largos sin remate"],
  },
  {
    id: "wholesome-moments",
    title: "Top momentos wholesome",
    category: "Emocional",
    angle: "clips positivos con giro tierno o final feliz",
    baseScore: 76,
    safetyScore: 94,
    retentionScore: 78,
    clipAvailabilityScore: 76,
    keywords: ["wholesome moments", "faith in humanity", "heartwarming clips", "momentos emotivos"],
    avoid: ["historias medicas explotativas", "menores identificables sin contexto", "drama fabricado"],
  },
  {
    id: "satisfying-clips",
    title: "Top clips satisfactorios",
    category: "Satisfying",
    angle: "procesos visuales con payoff hipnotico",
    baseScore: 75,
    safetyScore: 91,
    retentionScore: 80,
    clipAvailabilityScore: 84,
    keywords: ["satisfying videos", "oddly satisfying", "satisfying process", "videos satisfactorios"],
    avoid: ["clips repetidos sin sorpresa", "ruido molesto", "procesos peligrosos"],
  },
];
