export const STORY_FORMULAS = [
  "MESSAGE_FROM_FUTURE",
  "SECURITY_CAMERA",
  "IMPOSSIBLE_PHOTO",
  "AI_CONSCIOUSNESS",
  "UNKNOWN_SIGNAL",
  "DIGITAL_DOPPELGANGER",
] as const;

export type StoryFormula = (typeof STORY_FORMULAS)[number];

export const EPISODE_STATUS = {
  GENERATED: "GENERATED",
  REVIEWED: "REVIEWED",
  PUBLISHED: "PUBLISHED",
} as const;

export const MAX_HOOK_WORDS = 12;
export const MIN_DURATION_SECONDS = 10;
export const MAX_DURATION_SECONDS = 20;
export const WORDS_PER_SECOND = 2.5;
export const SIMILARITY_THRESHOLD = 0.8;
export const MAX_GENERATION_ATTEMPTS = 250;

export const RENDER_STATUS = {
  PENDING: "PENDING",
  SCENES_READY: "SCENES_READY",
  IMAGES_READY: "IMAGES_READY",
  AUDIO_READY: "AUDIO_READY",
  SUBTITLES_READY: "SUBTITLES_READY",
  RENDERING: "RENDERING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const YOUTUBE_UPLOAD_STATUS = {
  PENDING: "PENDING",
  UPLOADING: "UPLOADING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
} as const;
